package com.wevo.backend.ai.domain;

public enum AiErrorType {
    INVALID_REQUEST,
    PROVIDER_AUTHENTICATION,
    PROVIDER_PERMISSION,
    RATE_LIMITED,
    PROVIDER_TIMEOUT,
    PROVIDER_OVERLOADED,
    MODEL_NOT_AVAILABLE,
    PROVIDER_UNAVAILABLE,
    INVALID_RESPONSE,
    PROVIDER_REFUSAL,
    PROVIDER_MAX_TOKENS,
    JSON_PARSE_FAILED,
    SCHEMA_VALIDATION_FAILED,
    TYPE_CONVERSION_FAILED,
    SEMANTIC_VALIDATION_FAILED,
    PROVIDER_ERROR,
    INTERNAL_ERROR,
    ORPHANED_REQUEST
}
