package com.wevo.backend.ai.domain;

public enum AiErrorType {
    INVALID_REQUEST,
    PROVIDER_AUTHENTICATION,
    PROVIDER_PERMISSION,
    RATE_LIMITED,
    PROVIDER_TIMEOUT,
    PROVIDER_OVERLOADED,
    MODEL_NOT_AVAILABLE,
    PROVIDER_UNAVAILABLE,
    INVALID_RESPONSE,
    PROVIDER_ERROR,
    INTERNAL_ERROR,
    ORPHANED_REQUEST
}
