package com.wevo.backend.ai.client;

/** 구조화 출력 의미 검증 실패를 원문 없이 분류하는 저카디널리티 내부 코드. */
public enum StructuredOutputSemanticFailureReason {
    UNKNOWN,
    OUTPUT_REQUIRED,
    TEXT_INVALID,
    COLLECTION_REQUIRED,
    COLLECTION_EMPTY,
    COLLECTION_LIMIT_EXCEEDED,
    REFERENCE_DUPLICATED,
    REFERENCE_NOT_ALLOWED,
    COVERAGE_REFERENCE_DUPLICATED,
    COVERAGE_REFERENCE_UNEXPECTED,
    COVERAGE_REFERENCE_MISSING,
    ISSUE_INVALID,
    ISSUE_LIMIT_EXCEEDED,
    ISSUE_TYPE_LIMIT_EXCEEDED,
    CONFLICT_FIELDS_INVALID,
    CONFLICT_OPTION_INVALID,
    GAP_FIELDS_INVALID
}
