-- 입력 예산 초과를 일반 내부 오류와 구분해 AiJob 최종 실패 사유로 저장한다.
-- 기존 행 전체 스캔은 다음 마이그레이션의 VALIDATE CONSTRAINT 로 분리한다.
ALTER TABLE ai_jobs
    DROP CONSTRAINT chk_ai_jobs_final_error_type;

ALTER TABLE ai_jobs
    ADD CONSTRAINT chk_ai_jobs_final_error_type CHECK (final_error_type IS NULL OR final_error_type IN
        ('INVALID_REQUEST', 'PROVIDER_AUTHENTICATION', 'PROVIDER_PERMISSION', 'RATE_LIMITED',
         'PROVIDER_TIMEOUT', 'PROVIDER_OVERLOADED', 'MODEL_NOT_AVAILABLE', 'PROVIDER_UNAVAILABLE',
         'INVALID_RESPONSE', 'PROVIDER_REFUSAL', 'PROVIDER_MAX_TOKENS', 'JSON_PARSE_FAILED',
         'SCHEMA_VALIDATION_FAILED', 'TYPE_CONVERSION_FAILED', 'SEMANTIC_VALIDATION_FAILED',
         'INPUT_BUDGET_EXCEEDED', 'STALE_INPUT', 'APPLICATION_TIMEOUT',
         'WORKER_HEARTBEAT_TIMEOUT', 'PROVIDER_ERROR', 'INTERNAL_ERROR', 'ORPHANED_REQUEST'))
    NOT VALID;
